### ISSUE TITLE
Support min file size

### ISSUE THREAD

**Issue by vommuan** [pqina/filepond-plugin-file-validate-size#11]
It's needed to compatibility with [Yii2 FileValidator](https://www.yiiframework.com/doc/api/2.0/yii-validators-filevalidator#$minSize-detail).

I develop a module for this framework to connect FilePond.

See also: [tooSmall parameter](https://www.yiiframework.com/doc/api/2.0/yii-validators-filevalidator#$tooSmall-detail)

**Comment by rikschennink** [comment]
What is the use case for this in real life? Why would I set a min file size?

**Comment by vommuan** [comment]
Use case in real life. For example, I want to upload video file. And I know, that minimum size of video in FullHD is 1 MB. So, if user will try to upload file, which is less than 1 MB, I can tell him about error before uploading this file on server.

**Comment by rikschennink** [comment]
@vommuan okay, and why is the `minFileSize` property not covering this use case?

**Comment by rikschennink** [comment]
@vommuan I see it's not documented :D My mistake. :)
