### ISSUE TITLE
Validation error not bubbling up when dropped

### ISSUE THREAD

**Issue by jmhellman** [pqina/filepond-plugin-file-validate-size#13]
I'm experiencing an issue using both the validate size and validate type plugins where they are simply rejecting the file on drop with no error bubbling up - no `onerror` event triggering. However, when adding the files through the file picker interface it functions as expected where the file is added to the dropzone and highlights red with an error label.

Is this known/expected? Based on how it looks like the plugin is coded, I'm confused as to how the experience could differ between the two interactions. I do plan to keep digging.

**Comment by rikschennink** [comment]
Maybe `dropValidation` is set to `true`?

**Comment by jmhellman** [comment]
My apologies -- you're absolutely right. This was a complete misunderstanding of what that flag did -- I assumed it meant "turn on validation for drops" but its more "use the validation to reject files on the drops". Documentation was pretty clear on what it did once I looked at it -- sorry for wasting your time!!!

**Comment by rikschennink** [comment]
@jmhellman no worries, glad it’s working 👍
