### ISSUE TITLE
Options not registered when using `FilePond.setOptions`

### ISSUE THREAD

**Issue by 3ace** [pqina/filepond-plugin-file-validate-size#14]
I've just started using FilePond to display a couple drop area in single page. 

Currently I'm having trouble setting this plugin up because it looks like this plugin won't work when I'm using `FilePond.setOptions` and `FilePond.parse()`.

You can test that in https://jsfiddle.net/sbx6Ltn0/1/

**Comment by rikschennink** [comment]
It's `maxFileSize`
