### ISSUE TITLE
Support minFileSize?

### ISSUE THREAD

**Issue by manfromanotherland** [pqina/filepond-plugin-file-validate-size#2]
First, thanks for the amazing plugin, filepond absolutely rocks!

I was wondering if would be possible to validate file sizes based on `minFileSize` as well? The documentation says it supports `maxFileSize` but haven't encountered anything about min file size.

Thank you.

**Comment by rikschennink** [comment]
Hi, Thanks so much, so glad you like it!

There currently is not, I wonder, what would be the use case for testing a min file size?

**Comment by manfromanotherland** [comment]
Thanks for getting back so quickly.

The use case is to filter out 0 bytes files. For example, if I create a PDF file with 0 bytes (say using `touch file.pdf` on command line) the file is still accepted as valid PDF.

Not a huge issue really, just trying to prevent users to upload invalid/empty PDF files.

**Comment by rikschennink** [comment]
Hm okay I understand, I'm wondering if 0-byte files would be useful in any situation or if it would be nice if FilePond filtered them by default.

**Comment by rikschennink** [comment]
~I'm extending the FilePond `ignoredFiles` property with the option to set a function instead of a string. Should be online later today.~

Choose to go with `minFileSize` instead as it might be relevant for the user to see that the file is not allowed.

**Comment by rikschennink** [comment]
Now available in version `2.1.0`, please confirm it functions correctly

**Comment by manfromanotherland** [comment]
It functions perfectly. Thanks Rik! 👍
