### ISSUE TITLE
file don't upload above 1mb

### ISSUE THREAD

**Issue by dinesh-ravi** [pqina/filepond-plugin-file-validate-size#24]
const pond = FilePond.create(inputElement);
        FilePond.registerPlugin(
        FilePondPluginFileValidateType,
        FilePondPluginFileValidateSize,
    );
FilePond.setOptions
({
      allowMultiple: true,
      allowFileSizeValidation: true,
      maxFileSize: '10MB',
      server: {
                url: '/upload',
                method: 'POST',
              
                headers: {
                    'X-CSRF-TOKEN': '{{ csrf_token() }}'
                }
            }

        });

**Comment by rikschennink** [comment]
Will close because of low effort issue description, please offer a test case on codesandbox.
