### ISSUE TITLE
minFileSize and maxFileSize should be included in allowed file sizes

### ISSUE THREAD

**Issue by iadcode** [pqina/filepond-plugin-file-validate-size#25]
Files that have a size that equals minFileSize or maxFileSize are currently not valid file sizes. Given that these are the min and max allowed size, then they should be included in the allowed range.

E.g.
```js
import 'filepond/dist/filepond.min.css';

import FilePondPluginValidateSize  from 'filepond-plugin-file-validate-size'
import { create, registerPlugin } from 'filepond';

registerPlugin(FilePondPluginValidateSize);

const inputElement = document.querySelector('input[type="file"]');

create(inputElement, {
  allowMultiple: true,
  minFileSize: 1,
  maxFileSize: 4
});
```
In the example above, if you upload a file that has a size of exactly 1 byte or 4 bytes you will see the following:
![image](https://user-images.githubusercontent.com/18545429/167526116-9d77609e-c237-4ca9-88a2-4becf6b07871.png)

**Comment by rikschennink** [comment]
thanks for the PR, merged, will release new version later today
