### ISSUE TITLE
File Size Validation doesn't invalidate Form it is wrapped in

### ISSUE THREAD

**Issue by SushanRajShakya** [pqina/filepond-plugin-file-validate-size#4]
File Size Validation works fine but the Form that wraps the FilePond, the Form's validity is not set to invalid when there are files whose size is greater than the maxFileSize.

```jsx
<form ref={red => this.form = ref} onSubmit={(e) => {
     e.preventDefault();
     console.log(this.form.checkValidity())
   }}>
   <FilePond maxFileSize='1MB'/>
   <button type="submit">submit</button>
</form>
```

The above code give me valid form when i have files that exceed the maxFileSize in the FilePond

**Comment by rikschennink** [comment]
Just published version `3.9.0` of FilePond, it now contains two additional properties.

`checkValidity` which is set to `false` by default. If it's set to `true`, FilePond will set the contents of the `labelInvalidField` property as the field custom validity message.

```jsx
<FilePond checkValidity={true} maxFileSize='1MB'/>
```

![screenshot 2019-02-04 at 09 41 38](https://user-images.githubusercontent.com/1132575/52197786-19b8f000-2861-11e9-92dc-caaf80a4adfb.png)

**Comment by muzamuba** [comment]
If I add this property <FilePond checkValidity={true} maxFileSize='1MB'/> together with allowmultiple property, and try to add two files one under 1MB and the other one more than 1MB size, it fails validation, and rightly that is the expected result. But if I try to remove the second file it does not pass the validation. And the customValidity doesnot resets to empty string.

**Comment by SushanRajShakya** [comment]
Thank you @rikschennink for the addition of the above property.
